setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160315_ghc-7.10.2:
        url: https://github.com/nrolland/ghcjs/releases/download/v.0.2.0.20160315/ghcjs-0.2.0.20160315.tar.gz
compiler-check: match-exact
compiler: ghcjs-0.2.0.20160315_ghc-7.10.2

resolver: lts-5.9

extra-deps:
- ghcjs-dom-0.2.3.1
- data-default-class-0.0.1 # Needed for ghcjs-jquery to install
#- blaze-builder-0.4.0.1

flags: {}

packages:
- .
- location:
    git: https://github.com/ghcjs/ghcjs-jquery.git
    commit: 6e8023229342eaf78204cde3189865be891e5aa4
